# This is a basic workflow to help you get started with Actions

name: Busytest

on:
  workflow_dispatch:

jobs:
  busybox_test:
    name: Busybox test suite
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest }
    steps:
    - uses: actions/checkout@v1
    - name: Install `rust` toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        profile: minimal # minimal component installation (ie, no documentation)
    - name: "prepare busytest"
      shell: bash
      run: |
        make prepare-busytest
    - name: "run busybox testsuite"
      shell: bash
      run: |
        bindir=$(pwd)/target/debug
        cd tmp/busybox-*/testsuite
        ./runtest
